### ISSUE TITLE
Centrale random crash

### ISSUE THREAD

**Issue by timostrating** [HTML-as-programming-language/project-software#6]
I randomly got this crash when I removed a module.

![screenshot_2018-11-08_14-08-21](https://user-images.githubusercontent.com/12185305/48200796-83a82300-e360-11e8-998a-1a2fb8943f34.png)

**Comment by githubisforhipsters** [comment]
Komt omdat je URL die je met /init meestuurt niet valid is
In je screenshot is het "htpp://..."

Op zich zou de server alle input van third-party clients moeten checken. Maar ik vertrouw jullie <3

**Comment by hilkojj** [comment]
👌👌👌
